### ISSUE TITLE
Retours Search

### ISSUE THREAD

**Issue by Lnamw** [Infomaniak/ios-mail#297]
- [x] Ajouter filtre à la pagination
- [x] Effacer la sélection quand on part de la recherche ?
- [x] Etendre le clic de la sélection du dossier (doit taper sur le mot, ne marche pas sur les encoches de chaque coté)
- [x] Ajouter un loader
- [ ] Ajouter une vue vide si la recherche ne trouve rien
- [ ] Revoir Animation
- [x] Quand on clique sur un filtre l'historique apparait brièvement
- [x] Quand on clean le champ de recherche est-ce qu'on veut pas aussi effacer la liste de thread correspondant à la recherche qu'on vient d'effacer? 
- [x] Les filtres sont blancs en dark mode
- [x] En landscape l'arrondi du champ de recherche n'est pas très arrondi (revoir landscape)
- [x] Est-ce qu'on désactiverait pas le force refresh sur la search?

iPad:
- [x] Grand espace entre champ de recherche et les filtres
- [x] La recherche ne fonctionne pas sur iPad

**Comment by PhilippeWeidmann** [comment]
- [ ] Crash quand on refresh pendant une recherche (essayer plusieurs fois de refresh à différent moment pour l'obtenir)

**Comment by valentinperignon** [comment]
- [ ] "All folders" non traduit
- [ ] Le chevron du bouton "All folders" n'est pas pris en compte (pas d'action si on appuie dessus)
- [ ] Chevron de retour en arrière de la mauvaise couleur (rose plutôt que gris)
- [ ] Est-ce que la loupe doit agir comme un bouton ?
- [ ] Dans la liste de messages, les sections sticky ne s'affichent pas correctement
- [ ] Quand je tape quelque chose, puis que je vide le champ avec le bouton, les résultats ne sont pas toujours modifiés
- [ ] Crash "Cannot register notification blocks from within write transactions." quand on revient à la ThreadList parfois
- [ ] Placeholder "SearchField" à modifier 

À revoir avec Myriam : 
- [ ] Je crois que quand le search field n'est plus sélectionné, on ne doit plus afficher les contacts
- [ ] C'est bizarre, dans la liste des filtres, d'avoir des filtres exclusifs (Lus/Non Lus/Favoris) et non exclusifs (Pièces-Jointes/Tous les dossiers) sur la même ligne
